### ISSUE TITLE
[Model Update]:  SerialPart 2.0.0 Update Meta Model to SAMM 2.0.0

### ISSUE THREAD

**Issue by bs-jokri** [eclipse-tractusx/sldt-semantic-models#292]
## Update Reason
SerialPart 1.0.1 is still BAMM 2.0.0 and can therefore not be used in SAMM Models. This request is about to update the meta model to SAMM 2.0.0 

## MS1 Criteria

- [ ] The model that should be updated exists
- [ ] The referenced use case exists
- [ ] The potential updates are discussed with all stakeholders
- [ ] A decision on versioning was made in consensus with the affected parties [according to the guidelines](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/documentation/GOVERNANCE.md#versioning).
- [ ] The potential update will be either 
  - [ ] backward compatible or 
  - [ ] a (chain of) migration strategy(-ies) from all non-deprecated previous versions to the new model will be developed

**Comment by bs-jokri** [comment]
closed by https://github.com/eclipse-tractusx/sldt-semantic-models/pull/291
